### ISSUE TITLE
Request R package `ottr` for class PS 3

### ISSUE THREAD

**Issue by dbroockman** [berkeley-dsep-infra/hubs#2656]
**Which package do you want installed?**
`ottr` v1.0.0, as installed from `devtools::install_github("ucbds-infra/ottr@stable")`

**Which hub do you want it installed on?  For example r.datahub, datahub, data100.datahub, etc.**
r.datahub

**Which class will use this package?**
PS 3 Fall 2021, Professor David Broockman

**Which semester will this package be used for?**
Fall 2021
Class starts today and we are getting errors because r.datahub has an old version of `ottr`

**Any additional information we should know about?**
#2639 appears to have updated the version of the Python otter package, but we need an update of the `ottr` package for R.

In the attached output I show that UCB Datahub is currently running v0.9 of `ottr`, but after running `devtools::install_github("ucbds-infra/ottr@stable")` it upgrades to v1.0.0.

Can we get the latest `ottr` version from `devtools::install_github("ucbds-infra/ottr@stable")` installed in R on Datahub?

[Week2_Activity1.pdf](https://github.com/berkeley-dsep-infra/datahub/files/7081776/Week2_Activity1.pdf)

**Comment by balajialg** [comment]
@dbroockman Do you have any time constraints with regards to the installation of this package?

**Comment by dbroockman** [comment]
We have class at 5 pm today. The notebooks throw an error because the package is out of date.

**Comment by balajialg** [comment]
@dbroockman Thanks for your response.  Since our image build takes at least 3 hours, I want to confirm if any other package needs to be installed before your class today?

We understand the constraints at your end today trying to set up the environment for this class! From now on, if you could do the following, it would make life easier for us and help us improve the stability of the hub.
1. Before the start of the semester, Can you request all the packages at once that need to be installed in the R hub?
2. Can you test out these packages in your instance of the hub to check for any conflicts with other packages before making this request?

**Comment by dbroockman** [comment]
Thanks so much, and I'm really really sorry for the rush.

Yes, we've been working on the class all summer and have been testing everything along the way, including on DataHub. This issue arose because the the Otter grader itself was updated recently, and the updated version of Otter grader now compiles to notebooks that are not backwards compatible with the old `ottr` R package that is live on Datahub.

Locally I have the latest version of the `ottr` R package and there are no issues with it. Likewise when I run `devtools::install_github("ucbds-infra/ottr@stable")` on r.datahub, the notebooks then run fine.

**Comment by balajialg** [comment]
@dbroockman Thanks for your response! We can understand the challenge at your end. 

We will communicate once the package gets installed.

**Comment by yuvipanda** [comment]
@dbroockman try now?

**Comment by dbroockman** [comment]
It works now! Thank you!!!

**Comment by yuvipanda** [comment]
@dbroockman how did the class go?

**Comment by dbroockman** [comment]
Worked great!! Thank you!!!
