### ISSUE TITLE
Non-persistent installations

### ISSUE THREAD

**Issue by adamgayoso** [berkeley-dsep-infra/hubs#2755]
### Bug description

Not sure if this is by design or a bug, but for BioE 131 students need to install special bioinformatics packages through conda for each lab. Some are used across labs. The installations are not persistent after logging out of datahub and logging back in (after some period of time)

### Environment & setup

- Hub: 
- Language: 

Datahub, Python

### How to reproduce

Install any python package with pip or conda, after a few days (or hours?) It needs to be reinstalled.

**Comment by balajialg** [comment]
@adamgayoso Hi Adam, It is by design. You can install packages in a specific hub by raising requests [here](https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=&labels=support&template=datahub-package-addition---change-request.md&title=Request+python+package+X+for+class+Y)! That way, your installations will persist across multiple sessions
