### ISSUE TITLE
Stat 20 DataHub

### ISSUE THREAD

**Issue by andrewpbray** [berkeley-dsep-infra/hubs#3137]
# Summary

I'll be teaching Stat 20 to 600+ students this spring semester and am wondering: is it possible / sensible to have them compute at stat20.datahub.berkeley.edu instead of at r.datahub.berkeley.edu as I did last semester?

# Important information

- Most of the computing is done in live labs spread across Thursday.
- Assignments are due Monday at 10 pm, so there will be a peak load prior to that.
- The computing is restricting to stuff within the RStudio IDE

Thanks!

**Comment by ryanlovett** [comment]
@andrewpbray mentioned in an email thread that he will be making frequent changes to the R environment throughout the term. A separate, smaller singleuser image would probably make deployments faster.

**Comment by yuvipanda** [comment]
This sounds good. @ryanlovett do you think you have bandwidth to try creating this hub, following template at https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/template? Look at https://github.com/berkeley-dsep-infra/datahub/pull/3116 for an example around setting up the auth with datahub-staging and datahub (rather than bcourses themselves). 

Agree that a smaller image will make management easier. I'd suggest copying https://github.com/berkeley-dsep-infra/datahub/tree/staging/deployments/publichealth/image and removing the PH specific parts of it, so we base it off the rocker images.

**Comment by ryanlovett** [comment]
Yep! I have time this week.

**Comment by ryanlovett** [comment]
Fixed by by #3159.
