### ISSUE TITLE
GitHub Authentication in the Hub for STAT 159/259

### ISSUE THREAD

**Issue by facusapienza21** [berkeley-dsep-infra/hubs#3167]
Hi! I just wanted to check and see what is the best strategy and how should I proceed in order to set the GitHub SSH credentials for students in the course. Thank you very much!!!

**Comment by fperez** [comment]
Actually I think we should phrase this as "authenticated push/pull from the hub" - if confguring credential management over https is easier than over SSH, that's perfectly fine. We would just like to offer the students a reasonably smooth workflow for authenticated push/pull, but it doesn't have to be using SSH at all. Whichever solution is cleaner works for us.

**Comment by yuvipanda** [comment]
@fperez @facusapienza21 I spent some time on this today, building out a new package that lets you *securely* authenticate to GitHub from JupyterHub (and other remote clusters, like HPC centers too): https://github.com/yuvipanda/github-app-user-auth. The primary reason is to provide better security than ssh-keys left on the JupyterHub - I've copied the [goals section](https://github.com/yuvipanda/github-app-user-auth#goals) here for convenience.


1. Allow users on a JupyterHub to grant push access to only specific repositories rather than all the repositories they have access to.
2. Do not store long-term credentials (like personal access tokens or ssh-keys) on disk, as they may get archived / fall into the wrong hands in the future.
3. Allow GitHub organization admins visibility and control over what repos users can push to from remote systems (like JupyterHub or a shared cluster), where other admins of the remote system might be able to access the files of users with push access to repos. This has serious implications for supply chain security, as credentials might be stolen or lost and serious vulnerabilities be pushed to the repo.

I've also written about the [alternatives considered](https://github.com/yuvipanda/github-app-user-auth#alternatives).

It's currently deployed on stat159.datahub.berkeley.edu.

Here's how you can use it.

1. Go to https://github.com/apps/stat159-berkeley-datahub-access, and 'Install' the app. Give it access to whichever repositories you want to *push* to. You can come back and add more repos here later if you wish.
2. Login to stat159.datahub.berkeley.edu, and open a terminal.
3. Run `github-app-user-auth` on the terminal. It'll tell you to open a link in your browser, and input a 6 character code it gives you in the page opened.
4. Once done, 'Accept' and it'll ask you if you want to authenticate.
5. Once accepted, you're done! You can now push to the repositories you gave access to in step 1 for the next 8 hours or until your server stops from inactivity! We'll hopefully have a quick 'sign in' button at some point that can make this a bit more streamlined, but this should work nicely already.

@fperez @facusapienza21 try it out and let me know?

**Comment by fperez** [comment]
This is fabulous, thanks so much Yuvi. Immensely appreciated!!

@consideRatio - I figured I'd point you to this, we may want to deploy it on juptyearth and I think in general it will be a great resource to use hubs as good everday dev homes.

**Comment by yuvipanda** [comment]
@fperez yw :) I'm very happy to have an alternative to your private ssh keys existing on a JupyterHub! Let me know how this goes.

**Comment by fperez** [comment]
BTW, I think this can be closed - we may return with feedback for refinements, but I've tested it quite a bit and the basics are solid, so to keep your backlog clean, it's fine to close this one.

Thanks again so much.

**Comment by yuvipanda** [comment]
So glad you like this, @fperez!
