### ISSUE TITLE
Request 8 GB RAM for Stat 159

### ISSUE THREAD

**Issue by fperez** [berkeley-dsep-infra/hubs#3296]
**Which hub do you want more RAM on?**

For example: stat 159/259

**Which class is this request for?**

https://classes.berkeley.edu/content/2022-spring-stat-159-001-lec-001

**How many students do you expect in this class?**

70

**How much RAM does this class need?**

8 GB

**Why does this class need this much RAM?**

We're analyzing climate data as part of the course, and these are inherently large.  The prior bump to 4gb was big help, but students are still having kernels die way too often due to insufficient RAM. I'd very much appreciate having memory bumped again to 8GB.

**By when (MM/DD) do you want this request to be fulfilled?**

As soon as is viable - today students struggled a lot more than we thought they would due to RAM limitations, so we decided to request a bump.  I understand mid-semester requests are a hassle and I apologize, but we're exploring new data in a course that is still in-development, so it's hard for me to predict fully in advance the scope of our needs.

Many thanks for the help!

cc @facusapienza21 (class GSI).

**Comment by balajialg** [comment]
@fperez Thanks for the detailed inputs! Do you foresee the RAM bump remaining as a steady-state for Stat 159 hub till the end of the semester or only specific to a few assignments?

**Comment by fperez** [comment]
It's hard to tell, so if it's not a big burden, I'd prefer keeping it on. Upcoming assignments will be very open-ended, with real-world datasets the students themselves will fetch, as the course is intended to bridge with published research (the dataset that triggered this request corresponds to a recently published climate paper).

Given this nature of the course, and that we have a substantial fraction of graduate students with research experience who are likely to push the limits of the system, I'd prefer to keep it at 8gb if possible for the remainder of the term.

Now, I don't know how much work it would be, but one thing we do in our research hub is to have the extra landing page with a node selector:

![image](https://user-images.githubusercontent.com/57394/157299511-f6e3117f-4a67-4b0a-8da0-d9d985eb90fd.png)

I'm starting to think that for a course like 1/259, this would actually be a perfect solution. My students are experienced enough not to get confused by this (which would probably be too much for Data8 and similar), and I could tell them to use the smallest node by default, bumping up to the bigger ones as needed.

That would probably help keep costs down, while giving us head room when appropriate.

I understand if it's too much to request mid-semester, but it's an idea to consider :)

**Comment by balajialg** [comment]
@fperez Just created a PR to bump the RAM guaranteed and allocated to 8 GB for Stat 159 hub. Should get merged to prod hopefully before EOD today. 

@felder and I had a detailed discussion internally regarding the cost implication for this change. We currently foresee it to be manageable and under control. We will get back to you by the end of the semester if we think cloud costs are a concern. Hoping that this arrangement works for you! In addition, if there are times you expect the students to use the hub simultaneously and as a result require additional compute for the hub, we can always provision more compute resources dynamically using the [calendar-based auto scaler.
](https://github.com/berkeley-dsep-infra/datahub/pull/2681)

Related to your request about node selector, this feature is not enabled in any of the Berkeley hubs. Stat 159 hub could be a great way to develop a proof of concept for this feature. Considering its implications for RAM usage and cloud costs, it seems like a value add even from a hub admin perspective. Having said that, I don't know the effort involved to enable this feature! Tagging @yuvipanda so that he can add his perspective on both desirability/feasibility.

**Comment by fperez** [comment]
Thanks a ton for the prompt and kind response, @balajialg, my students will very much appreciate it!

And glad to continue iterating on ideas to gain both flexibility and cost efficiency - the node selector option is very valuable in that regard (and just to clarify, I didn't mean we'd need the exact same options as shown in that screenshot, but for example having a few tiers of CPU/RAM would likely suffice for a class like 159).

**Comment by balajialg** [comment]
@fperez Happy to be of some help! Let's keep this conversation going about enabling node selectors for Stat 159!

**Comment by fperez** [comment]
Closing this as I see the 8GB are now working, thanks so much team!!
