### ISSUE TITLE
This change seems not to have carried over into 2022--students have instances with 1 GB of RAM.  Can we re-up to 4GB?

### ISSUE THREAD

**Issue by ligon** [berkeley-dsep-infra/hubs#3329]
This change seems not to have carried over into 2022--students have instances with 1 GB of RAM.  Can we re-up to 4GB for students in ENVECON153, please?

_Originally posted by @ligon in https://github.com/berkeley-dsep-infra/datahub/issues/2013#issuecomment-1083671412_

**Comment by felder** [comment]
@ligon Can you please open a new issue using the issue template for this?

https://github.com/berkeley-dsep-infra/datahub/issues/new?assignees=balajialg&labels=support&template=higher-resources.md&title=Request+more+RAM+for+class+X

These changes will not carry over because they are based on specific values for each term and year including the courses' SIS ID which changes every semester. This means every semester you'll need to put in a request.

Alternatively depending on use case, it may make sense to have a separate hub.
