### ISSUE TITLE
Request retrieval of my Datahub files

### ISSUE THREAD

**Issue by lbiral** [berkeley-dsep-infra/hubs#3487]
### Email Id

lbiral@berkeley.edu

### Link to Datahub Folder

[- Eg: gs://ucb-datahub-archived-homedirs/spring-2021/datahub.berkeley.edu/xxx.tar.gz](https://datahub.berkeley.edu/hub/login?next=%2Fhub%2Fuser%2Flbiral%2Ftree)

**Comment by felder** [comment]
@lbiral 

I need the link that is in the file that led you here.

**Comment by lbiral** [comment]
> @lbiral
> 
> I need the link that is in the file that led you here.

Let me know if this one works: https://datahub.berkeley.edu/hub/login?next=%2Fhub%2F

**Comment by felder** [comment]
@lbiral no.  I need the link from the document in your home directory.  It's of a similar format as the one in the issue description.

**Comment by lbiral** [comment]
I'm sorry, but I am so confused. Which document in my home directory? I can't access my home directory because my DataHub is shut down. If it's not this one (https://datahub.berkeley.edu/user/lbiral/tree), then I have no idea.

**Comment by felder** [comment]
@lbiral Login via https://datahub.berkeley.edu

Requesting file retrieval only makes sense if you have some indication your files have been archived.  The way we inform you is by placing a file in your home directory which contains instructions to come here and tell us which archive to retrieve.

**Comment by lbiral** [comment]
I never saw a file placed in my home directory. I tried logging in the other day and I got a message saying "Canvas doesn't have an account for user: 1558987" 

I have a lot of important personal and professional files on there so I would really love it if I could get them back.

**Comment by felder** [comment]
We're going to update the issue template to talk about this, but yeah the idea behind archive retrieval requests is that we periodically archive files and inform people that this has been done via a file we place in their home directory.  That file contains instructions to open an issue here and provide the link in that file that tells me which archive to retrieve.

If someone opts to open an issue for file retrieval and was not directed to do so by the above process, then it causes a fair amount of confusion if they attempt to construct their own links.  That sends me on a wild goose chase of sorts and results in confusion.

So I think the first issue to look at here, is why you're unable to login.  It's either a technical issue which we need to address or it's because you're no longer a student at UC Berkeley.  If it's the latter, can you please tell me what courses you took that used datahub and what semesters you took them?  If it's the former, that's the issue we need to address.

**Comment by lbiral** [comment]
I think the issue is that I am no longer a student. I believe all the courses I took that used Datahub were Data 8 (spring 2019), Data 100 (fall 2020), IndEng 142 (spring 2021), and Stat 140 (fall 2019)

**Comment by felder** [comment]
2 signed URLs sent.

**Comment by felder** [comment]
Found unarchived files, manually archived them, and sent a third signed URL.

**Comment by lbiral** [comment]
Fantastic! Thank you so much!

**Comment by balajialg** [comment]
Super cool @felder! Thanks for all your hard work here.

**Comment by felder** [comment]
@lbiral Please feel free to reopen this if you're still missing something.
