### ISSUE TITLE
Request R package ipumsR for class Econ 140 

### ISSUE THREAD

**Issue by ericvd-ucb** [berkeley-dsep-infra/hubs#3757]
### Package Name

ipumsr

### Hub details

- Hub: R hub
- Language: R 

### Course Name

Econ 140 - Ryan Edwards

### Semester Details

Fall 22 and into the future

### Installation Deadline

Not sure
@ryanlovett 
@ryanedw

**Comment by felder** [comment]
@ryanlovett you were doing some work around installing the dependencies for this right?

**Comment by ryanlovett** [comment]
@felder There shouldn't be any additional work regarding dependencies -- the existing installation process we have will work for this. It is just that a conversation about this particular library led to the realization around the HTTP user agent string. This was because installing from source failed, from within jupyter in the single user environment. Installing from CI should pull in binaries.

**Comment by felder** [comment]
Done!
