### ISSUE TITLE
Request python package ipython-sql and its dependency for Data 100

### ISSUE THREAD

**Issue by andrea2031** [berkeley-dsep-infra/hubs#3897]
### Package Name

ipython-sql-0.4.1, prettytable-0.7.2, and sqlparse-0.4.3

### Hub details

Datahub, Data 100
Python

### Course Name

https://classes.berkeley.edu/content/2022-fall-data-c100-001-lec-001

### Semester Details

Fall 2022

### Installation Deadline

Preferably as soon as possible, November 3rd the latest. Sorry for the late notice.

**Comment by felder** [comment]
@fperez the latest version of ipython-sql in conda forge is 0.3.9, will that suffice?

https://anaconda.org/conda-forge/ipython-sql

**Comment by felder** [comment]
Also looks like prettytable 3.4.1 is what's going to get pulled in:

```
(notebook) jovyan@jupyter-felder:~$ mamba install ipython-sql

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.7.4) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['ipython-sql']

pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/r/linux-64          [====================] (00m:00s) Done
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/main/linux-64       [====================] (00m:01s) Done
conda-forge/noarch       [====================] (00m:04s) Done
conda-forge/linux-64     [====================] (00m:08s) Done
Transaction

  Prefix: /srv/conda/envs/notebook

  Updating specs:

   - ipython-sql


  Package             Version  Build              Channel                    Size
───────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────

  ipython-sql           0.3.9  py39hde42818_1002  conda-forge/linux-64      27 KB
  prettytable           3.4.1  pyhd8ed1ab_0       conda-forge/noarch        27 KB
  sqlparse              0.4.3  pyhd8ed1ab_0       conda-forge/noarch        35 KB
```

**Comment by felder** [comment]
This should be on prod in a few minutes.  Please reopen if the version of the packages deployed are an issue.

**Comment by fperez** [comment]
Awesome, thanks a lot @felder! Versions shouldn't be an issue, we're using only the most basic functionality, so we'll be OK.

**Comment by fperez** [comment]
Ouch @felder  - I just found out the hard way that v 0.3.9 does NOT have a key feature I was using, and that we actually need... The docs didn't make it clear that this is only a recent addition, and I thought it was there all along...

Could I please bug you to update to 0.4.1 from PyPI?

Very sorry for this unexpected hassle! Since I still had the PyPI version on my system, I didn't notice the problem til now, when all of a sudden code from Tuesday stopped working...

**Comment by fperez** [comment]
BTW - there's actually a PR [in the conda-forge feedstock](https://github.com/conda-forge/ipython-sql-feedstock/pull/19) updating the conda package to 0.4.1.. But it's been in limbo for a while.

I don't know how to get that un-wedged, perhaps you or @yuvipanda knows? Getting that fixed would be ideal, so we could rely on this package via mamba like everything else, but with a less stale version.

And in this case, it turns out I _really_ need that feature, b/c it lets me massively clean up the D100 SQL lectures. So having a functioning 0.4.1 is critical.

(btw, I'm fine if we use the PyPI version, just mentioning the conda-forge PR in case that can lead to a cleaner option in the long run).

**Comment by yuvipanda** [comment]
@fperez i just installed ipython-sql from pypi, should be deployed in a few minutes

**Comment by fperez** [comment]
Huge thanks @yuvipanda and sorry for the messy back and forth!
