### ISSUE TITLE
Increase compute resources for EE 120 from Fri 03/03 through Sun 03/05

### ISSUE THREAD

**Issue by NSagan271** [berkeley-dsep-infra/hubs#4299]
### Course Name

https://classes.berkeley.edu/content/2023-spring-eleng-120-001-lec-001

### Detailed Requirements

- Deadline for EE 120 Lab 2 on Friday, with a grace period until Sunday night.

Same as https://github.com/berkeley-dsep-infra/datahub/issues/4215; we expect most of the students in the course to be working on the lab during this time period, but we don't know for certain.

### Semester Details

Yes

### Request Deadline

Friday, 03/03 at 8am to Monday, 03/06 whenever convenient

**Comment by balajialg** [comment]
Looking at the data between the 17th and 20th of last month, it seems like the allocated resources should be enough for students to work on their assignments. The additional resource requested might serve more as an insurance policy rather than solving a need.

![image](https://user-images.githubusercontent.com/2306166/222245814-5e436660-ceb6-4a83-aa5b-c1bda7e73083.png)

This is the general allocation during the last week. for the hub your course uses 
![image](https://user-images.githubusercontent.com/2306166/222246111-758f4b75-d660-4b0b-805b-94b2166eab27.png)

@NSagan271 We have been facing issues with supporting this request as the script that reads these calendar events sometimes doesn't parse certain calendar events. We are investigating the reasons for this behavior currently. So, I will manually bump up the resources after monitoring our metrics for your hub during the highlighted days.

**Comment by balajialg** [comment]
Closing this issue as the request got resolved.
