### ISSUE TITLE
datahub.berkeley.edu notebooks suddenly produce an error message on any use of .hist. 

### ISSUE THREAD

**Issue by Montereytony** [berkeley-dsep-infra/hubs#5115]
### Bug description

 This code worked fine a few days ago.   Prof suspects it’s due to a library version change or similar.  Need a fix for UGBA88 students’ lab work.   

### Environment & setup

- Hub: Datahub
- Language: Python

### How to reproduce

# Import some useful functions
from numpy import *
from numpy.random import *
from datascience import *
from statsmodels.formula.api import *
# Define some useful functions
def correlation (array_1, array_2):
return corrcoef(array_1, array_2) •item(1)
# Customize Look of graphics
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
plt.rcParams['figure.dpi' ] = 60
%matplotlib inline
# Force display of all values
from IPython.core. interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# Handle some obnoxious warning messages
import warnings
warnings. filterwarnings ("ignore")

data.hist('AMOUNT', normed=False, bins=10, range=make_array(0,100))

#Error message attached.

![ugab88error](https://github.com/berkeley-dsep-infra/datahub/assets/20211627/802a1d0a-37c3-4a48-b584-e4c039c93374)

**Comment by ryanlovett** [comment]
Thanks @Montereytony for filing the issue.

Do you have the full path to a notebook in your or Richard's home directory where the problem is evident? In the sample code you provided, `data` is not defined.

Apparently numpy.int was [deprecated in numpy 1.20.0](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations) and [removed in 1.24.0](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations). We [pin numpy to 1.21.*](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/datahub/images/default/environment.yml#L18), however CI upgrades numpy to 1.25.2 when it reads requirements.txt.

I don't see any relevant recent commit that might have triggered this:
https://github.com/berkeley-dsep-infra/datahub/commits/staging/deployments/datahub/images/default

One potential workaround is to try running `numpy.int = numpy.int_` before the call in question.

Long term I think the image building needs to read in requirements.txt at the same time as it reads environment.yml.

**Comment by ryanlovett** [comment]
The instructor confirmed that inserting `numpy.int = numpy.int_` before the call to `.hist()` is an adequate workaround. He will notify students to have them modify their notebooks.

The larger issue #5117 about unexpected versions is still outstanding.
