### ISSUE TITLE
Allow user to toggle 'show hidden files'?

### ISSUE THREAD

**Issue by cboettig** [berkeley-dsep-infra/hubs#5825]
# Summary

In our course, ESPM-157, many features we would like to cover, including git, GitHub Actions, git lfs (used in huggingface), require access to hidden files.  (besides, we generally want students to understand what a hidden file is and feel confident working with it).  Historically we have used the RStudio editor, where this a dropdown on the File menu.  

In Jupyterhub, it looks like turning this on involves some additional steps? https://jupyterlab.readthedocs.io/en/latest/user/files.html#displaying-hidden-files  (I've tried toggling this in the settings editor menu, but it doesn't seem to have an effect.)

# Acceptance criteria

Users can choose to show or hide hidden files (dot files) using the View menu, as described in https://jupyterlab.readthedocs.io/en/latest/user/files.html#displaying-hidden-files

# Additional Notes

I know we have the vscode (OSS Code) editor available, which already supports this too, but I'm hoping to just stick with the JupyterLab interface for consistency & simplicity it offers....

**Comment by ryanlovett** [comment]
This is enabled in stat159 hub:

- https://github.com/berkeley-dsep-infra/datahub/issues/3160
- https://github.com/berkeley-dsep-infra/datahub/blob/a6008bb8d5be786879e4e46d419b836b5fb3247a/deployments/stat159/config/common.yaml#L92

**Comment by cboettig** [comment]
@ryanlovett thanks, that's great! I was looking for how to do this in values.yaml file and couldn't figure it out.  Is this documented somewhere?  `extraFiles.culling-config.data` doesn't seem like the most obvious path to find ContentsManager options...

**Comment by ryanlovett** [comment]
@cboettig I think Yuvi chose `culling-config` because that's the slug that references the [file contents](https://github.com/berkeley-dsep-infra/datahub/blob/a6008bb8d5be786879e4e46d419b836b5fb3247a/hub/values.yaml#L88) that gets mounted at `/etc/jupyter/jupyter_notebook_config.json`. At the time the contents contained configuration related to culling. This contents should probably be put in the file `/etc/jupyter/jupyter_server_config.json` instead since it impacts jupyter server. The slug should be named `jupyter_server_config.json` (like what 2i2c [does](https://github.com/2i2c-org/infrastructure/blob/11e76734d53aa49abf6cde18fb2c52559d9e4fec/helm-charts/basehub/values.yaml#L703C7-L703C33)) to make it clearer.

This particular config is documented [in JupyterLab](https://jupyterlab.readthedocs.io/en/latest/user/files.html#displaying-hidden-files) and [jupyter server](https://jupyter-server.readthedocs.io/en/latest/other/full-config.html). 

If someone else doesn't get to it, I can make a PR on Monday.

**Comment by balajialg** [comment]
I just saw the conversation and created #5830 to address the changes listed here. Ryan - happy to close my PR incase you have specific changes in mind.

**Comment by ryanlovett** [comment]
Thanks for submitting that @balajialg ! I recommend the changes mentioned in https://github.com/berkeley-dsep-infra/datahub/issues/5825#issuecomment-2198456856. (not using `culling-config` since it is misleading and using `/etc/jupyter/jupyter_server_config.json` as the filename -- see the 2i2c example)

**Comment by balajialg** [comment]
Ah, thanks (my bad)! I just updated the PR with a new commit
