### ISSUE TITLE
Request terminal package bwa for class IB134L

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6295]
### Package Name

bwa 

### Hub URL

biology.datahub.berkeley.edu

### Course Name

Practical Genomics IB134L
https://classes.berkeley.edu/content/2024-fall-integbi-134l-001-lec-001

### Semester Details

 Fall 2024

### Installation Deadline

By 10/7/2024. The lab that week will require bwa. Specifically bwa mem and bwa index. It need to run on the terminal on the Biology Datahub.

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo

Password: changeme
I put the necessary dlls in the archive

**Comment by shaneknapp** [comment]
is this the package you're requesting?  there's a bunch of different results when i search for `bwa`:  https://anaconda.org/bioconda/bwa

**Comment by caroluscha** [comment]
yep that's the right bwa

**Comment by caroluscha** [comment]
Also can we get seqtk installed as well. 
https://github.com/lh3/seqtk

**Comment by shaneknapp** [comment]
> Also can we get seqtk installed as well. https://github.com/lh3/seqtk

i will try.

right now, if we install the latest version of `bwa` via bioconda, `augustus` will be downgraded from 3.5.0 to 3.2.2:

```
  - augustus             3.5.0  pl5321hf46c7bb_1     bioconda                      
  + augustus             3.2.2  0                    bioconda/linux-64         23MB
```

so, i'm trying to install `augustus` via `apt` (instead of as a python packages) in a local build to confirm that the correct version is installed.

regarding `seqtk`:  this package needs to be built from source, and i'll give it a shot but this is not something we really support.  i'll see how it goes and will get back to you.

edit:  i also found a python package of unknown provenance...  https://anaconda.org/bioconda/seqtk

**Comment by caroluscha** [comment]
if seqtk is not possible BBtools works as well. 

https://jgi.doe.gov/data-and-tools/software-tools/bbtools/

**Comment by shaneknapp** [comment]
> if seqtk is not possible BBtools works as well.
> 
> https://jgi.doe.gov/data-and-tools/software-tools/bbtools/

again, same issue w/`seqtk`:  this is a package that we need to manually compile and install in the user image.  no guarantees.

**Comment by shaneknapp** [comment]
@caroluscha this will be live on biology-staging.datahub.berkeley.edu in about 10-15m.  please confirm that `bwa` and `seqtk` work as intended.  i was able to manage keeping `augustus` at 3.5.0

**Comment by shaneknapp** [comment]
ok it's live on biology-staging

**Comment by caroluscha** [comment]
It works for me. Thanks so much!

**Comment by shaneknapp** [comment]
ok, this is merging to prod and will be live in a few minutes!
