### ISSUE TITLE
Request update to R package patchwork for class ph142

### ISSUE THREAD

**Issue by paulamarm** [berkeley-dsep-infra/hubs#6349]
### Package Name

patchwork

### Hub URL

publichealth.datahub.berkeley.edu

### Course Name

Introduction to Probability and Statistics in Biology and Public Health

### Semester Details

Ongoing: Just needs update

### Installation Deadline

Ideally as soon as possible to prevent the instructors from manually making the update every time they use it in materials for lecture!
Currently seeing the following errors appear:
```{r first-sample-250-error, echo=F, eval=F}
## If you are getting an error message like the following:
# Error in Ops.data.frame(guide_loc, panel_loc) :
#'==' only defined for equally-sized data frames
## ... then the issue might be a stale version of the 'patchwork' library. 
## You may be able to clear it up by manually running the following *once*, and then restarting R:
remove.packages('patchwork')
install.packages('patchwork')
```
Thank you!

**Comment by felder** [comment]
@paulamarm can you provide me with what I'd need to enter into the R console to produce your error?

**Comment by felder** [comment]
@paulamarm also can you please confirm the version of patchwork you're requesting?

**Comment by balajialg** [comment]
@paulamarm We figured out that cloning the [PH142-fa24 github repository](https://github.com/ph142-ucb/ph142-fa24) and launching the [following notebook](https://github.com/ph142-ucb/ph142-fa24/blob/efbd1b21bf12ed280978bbf86880ae0ac0c9a15c/lec/Day-11_Intro-probability/Ch09_Intro-probability.Rmd#L257) allowed us to reproduce the issue that you reported. We would appreciate sharing such test cases as part of the request since it takes a lot of admin time to reproduce the issue with minimal information provided. In addition, we were unclear about the version that the package needs to get upgraded to (we eventually figured that it was version 1.3.0)

**Comment by shaneknapp** [comment]
built, tested and about to merge to prod:
```
> packageVersion('patchwork')
[1] ‘1.3.0’
```

https://github.com/berkeley-dsep-infra/datahub/pull/6356

**Comment by felder** [comment]
@paulamarm ok I actually made some significant changes to the image in order to fix a few other R packages that I noticed didn't install successfully as well as to update a number of components.

Details, if you're curious:  
https://github.com/berkeley-dsep-infra/publichealth-user-image/pull/5

I verified that the notebook @balajialg referenced earlier runs.  However, I highly encourage you to run some additional tests using other notebooks to ensure no issues have popped up.  If you'd like to do that, please login to https://publichealth-staging.datahub.berkeley.edu

**Comment by paulamarm** [comment]
I apologize for not including the requested information in my initial post; I was following the package request template which didn't ask about recreating any errors, with the addition of details I got from course staff.
Thank you for the administrative support!

With the staging environment, I was able to run the notebooks used in the class without issues and can also see the update to Patchwork. 

If there are any specific issues to be looking out for/testing with any specific notebooks, please let me know!
Thanks, Paula

**Comment by felder** [comment]
@paulamarm ok this should land on prod shortly.  People with running servers will need to restart them in order to get the updates.
