### ISSUE TITLE
Request package hisat2 and htseq for class IB134L

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6393]
### Package Name

hisat2, htseq

### Package Version

latest

### Hub URL

biology.datahub.berkeley.edu

### Reproducible test case

conda install bioconda::htseq
conda install bioconda::hisat2

### Course Name

Practical Genomics - IB134L

### Semester Details

 Fall 2024

### Installation Deadline

ASAP. We can have the students install their own versions but would like it to be installed on the datahub.

**Comment by balajialg** [comment]
@caroluscha You are welcome to add these packages directly to the image by creating a PR. However, we are currently encountering dependency conflicts when attempting to install `htseq`, which requires `matplotlib` version 1.2.1. Unfortunately, this conflicts with the currently installed version (3.9.2). We are unsure if downgrading matplotlib is feasible, and due to this conflict, we might not be able to support the installation of `htseq` on our end.

Could you try installing this package on your local server and investigate the issue? If you can show us how to install the package, we can try replicating it at our end.

For the future - We would greatly appreciate it if you could test all the notebooks ahead of time and submit any required packages before the start of the spring semester.

**Comment by felder** [comment]
@caroluscha To clarify, running mamba install bioconda::htseq from a terminal wants to pull in a really old version which wants to pull in matpotlib 1.2.1 which makes no sense.

Running mamba install bioconda::htseq==2.0.5 (the latest version and the only one using python 3.11 https://anaconda.org/bioconda/htseq/files) gives an error about openssl that doesn't seem to make sense because it wants a version where the dependency is already met.  We're working on that by attempting to upgrade mamba/conda.

Running conda install bioconda::htseq never completes when I run it from a terminal (mamba generally works better).

So, how are you having people install this successfully?

**Comment by caroluscha** [comment]
@balajialg do you have some documentations on how to add packages to an image. I saw that part and was confused on how to do that. 

@felder I was unable to htseq install and was hoping to get some help with that. If htseq can't be installed, we can also use subread which is a similar package. I was able to install subread with conda install bioconda::subread. 

Sorry for the trouble.

**Comment by balajialg** [comment]
@caroluscha I see that @shaneknapp has added some extensive documentation for [creating PRs](https://docs.datahub.berkeley.edu/admins/howto/new-image.html#submitting-a-pull-request) to repos like https://github.com/berkeley-dsep-infra/biology-user-image. @shaneknapp Would it be better to do a short meeting to demo the PR creation worklow to @caroluscha?

**Comment by shaneknapp** [comment]
@caroluscha the instructions on how to modify, build, test and create PRs is located here:  https://github.com/berkeley-dsep-infra/biology-user-image/blob/main/CONTRIBUTING.md

i'd be happy to have a quick meeting to go over getting this all set up!

**Comment by felder** [comment]
@caroluscha ok, if possible inability to install a package is good information to include in the issue description.

**Comment by caroluscha** [comment]
Yeah it would be great to get a demo. I want to look through the documentation first so I can get a better idea of what I'm looking at in the demo. I appreciate everyone's help. 

@felder Will do for future requests.

**Comment by shaneknapp** [comment]
the image is building and will be live on biology-staging later this evening:  https://github.com/berkeley-dsep-infra/biology-user-image/actions/runs/11450178495/job/31857163136

fwiw, this takes ~45m to build

**Comment by shaneknapp** [comment]
this is now live on biology-staging.d.b.e!

**Comment by caroluscha** [comment]
great it looks like it's working!

**Comment by shaneknapp** [comment]
we have some other testing to do tomorrow morning, and we'll merge this change to prod when we're done

**Comment by shaneknapp** [comment]
this is now live on prod...  enjoy!
