### ISSUE TITLE
Request more RAM for class IB134L

### ISSUE THREAD

**Issue by caroluscha** [berkeley-dsep-infra/hubs#6481]
**Which hub do you want more RAM on? Please link the URL to the hub while specifying the hub name**
[biology.datahub.berkeley](https://biology.datahub.berkeley.edu/)

For example: Datahub (datahub.berkeley,edu), R Hub (r.datahub.berkeley.edu hub), Data 100 Hub (data100.hub.berkeley.edu), EECS hub (eecs.datahub.berkeley.edu), etc

**Which class is this request for?**
IB134L - Practical genomics

For example, "2025 Spring, Robot Studies 101".

**What is the Academic Guide URL for this class?**
https://classes.berkeley.edu/content/2024-fall-integbi-134l-001-lec-001

For example, https://classes.berkeley.edu/content/2025-spring-robot-101-001-lec-001

**What is the bCourses URL for this class?**

https://bcourses.berkeley.edu/courses/1536425

For example, https://bcourses.berkeley.edu/courses/9876543

**How many students do you expect in this class?**

100

An approximate number would do.

**How much RAM per user is needed?**

8GB

The default is 1GB of RAM per student.

**Why does this class need this much RAM?**

A short justification for this resource request.

Some programs require more RAM to run like indexing genomes. We have subsampling steps to reduce computational resources needed however some steps still require more RAM. Higher RAM usage is only necessary for some steps of student projects and a majority of the time would not need the higher RAM. Although the higher RAM is necessary for key steps of their project. 

**By what date (MM/DD) do you want this request to be fulfilled?**

ASAP

This will help us with the prioritization of this request.

**Until when (MM/DD) do you require the additional RAM?**

12/13/2024

This will help us scale down resources when the RAM increase is no longer required

**Any additional information we should know about?**

Would you be able to increase storage space for the students as well. 20gb per student would be ideal but less is ok too.

**Comment by balajialg** [comment]
@caroluscha I just merged the [PR](https://github.com/berkeley-dsep-infra/datahub/pull/6484) that increases the RAM to 8 GB for users affiliated to your bcourses course. Let me know if you can see the changes in https://biology-staging.datahub.berkeley.edu/.

As of now, there is no way we can enforce storage limit for the user's home directory which has been a challenge for the Bio Hub. Having said that, I would recommend the following,

- Redesign the assignment so that it is not storage-intensive (not 20 GB per user as you highlighted)
- Try shared directories for storage if it meets your needs. I would recommend more testing before sharing assignments with students given what you observed last Friday.
- Proactively request students to delete/backup files that are no longer required (with regular updates). We will be monitoring bio hub storage regularly and will let you know the list of users who are using a lot of storage. You might need to reach out to them!

**Comment by caroluscha** [comment]
Thanks Balaji! 
I see the changes on the staging datahub!

For storage, we just need a large storage temporarily to subsample and then we tell students to delete the files after subsampling. And yes please let us know if there are any students of ours using and excessive amount of storage. It's difficult to standardize this because each students is picking out their own data to use. But we will have protocols and guidelines in minimize the computational resources necessary.

**Comment by balajialg** [comment]
@caroluscha Thanks a lot for having protocols/guidelines. It will make our lives easier. Changes are merged to https://biology.datahub.berkeley.edu/
